In [198]:
import pandas as pd
import numpy as np

In [199]:
movies = pd.read_csv(r"C:\Users\intekhab alam\Downloads\tmdb_5000_movies.csv.zip")
credits=pd.read_csv(r"C:\Users\intekhab alam\Downloads\tmdb_5000_credits.csv.zip")
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [200]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [201]:
print(movies.shape)
print(credits.shape)

(4803, 20)
(4803, 4)

In [202]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 5.4 MB

In [203]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 33.8 MB

In [204]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [205]:
credits.describe()

            movie_id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000

In [206]:
print(movies.duplicated().sum())
print(credits.duplicated().sum())

0
0

In [207]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [208]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [209]:
df=movies.merge(credits,on='title')
df.shape

(4809, 23)

In [210]:
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [211]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='str')

In [212]:
# budget,homepage , original_language ,popularity , production_companies ,release_date ,tagline ,etc are not in df from now

In [213]:
df=df[['movie_id','title','overview','genres','keywords','cast','crew']]
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [214]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   str
 2   overview  4806 non-null   str
 3   genres    4809 non-null   str
 4   keywords  4809 non-null   str
 5   cast      4809 non-null   str
 6   crew      4809 non-null   str
dtypes: int64(1), str(6)
memory usage: 37.0 MB

In [215]:
df.describe()

            movie_id
count    4809.000000
mean    57120.571429
std     88653.369849
min         5.000000
25%      9012.000000
50%     14624.000000
75%     58595.000000
max    459488.000000

In [216]:
df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [217]:
df.dropna(inplace=True)

In [218]:
df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [219]:
df.duplicated().sum()

0

In [220]:
df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [221]:
'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
import ast # ast module helps to convert string representation of list/dict into actual list/dict
ast.literal_eval(df.iloc[0].genres)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [223]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [224]:
df['genres']=df['genres'].apply(convert)

In [225]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [226]:
df['keywords']=df['keywords'].apply(convert)

In [227]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [228]:
def convert1(obj):
    L=[]
    counter =0
    for i in ast.literal_eval(obj):
        if counter != 3:
         L.append(i['name'])
         counter+=1
        else:
           break
    return L

In [229]:
df['cast']=df['cast'].apply(convert1)

In [230]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [231]:
df['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [232]:
def director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [233]:
df['crew']=df['crew'].apply(director)

In [234]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [235]:
df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [236]:
df['overview'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.'

In [237]:
df['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [238]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [239]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:
# remove spaces
df['genres'].apply(lambda x:[i.replace(" ","") for i in x]) # this will remove spaces from the genres list

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [241]:
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df['crew']=df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [242]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [243]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']

In [244]:
df.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [245]:
df['tags']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4806, dtype: object

In [246]:
new_df=df[['movie_id','title','tags']]

In [247]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [248]:
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: str

In [249]:
new_df.head(2)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."

In [250]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [253]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [254]:
vector.shape

(4806, 5000)

In [255]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [259]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [266]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [269]:
# stemming:['loved','love','loving']=>['love']
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [272]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [273]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [274]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: str

In [276]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)

In [ ]:
similarity[0] # similarity of first vector with itself is 1.0

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ])

In [278]:
similarity[1]

array([0.08964215, 1.        , 0.0625    , ..., 0.02635231, 0.        ,
       0.        ])

In [280]:
similarity[0]

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ])

In [ ]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print((new_df.iloc[i[0]].title)) # new_df.iloc[i[0]].title gives the title of the movie at index i[0]

In [295]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [292]:
new_df.iloc[1361]

movie_id                                                 2661
title                                                  Batman
tags        the dark knight of gotham city begins his war ...
Name: 1361, dtype: object

In [ ]:
new_df.iloc[1361].title

'Batman'

In [1]:
import sys
!"{sys.executable}" -m pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (26.3)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (1.14.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.84.0-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.15.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from tensorflow) (3.11.0)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.6.0-cp312-cp312-win_amd64.whl.metadata (8.8 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Collecting typing_extensions>=3.6.6 (from tensorflow)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: rich in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (13.7.1)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.20.0-cp312-cp312-win_amd64.whl.metadata (33 kB)
Collecting numpy>=1.26.0 (from tensorflow)
  Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\intekhab alam\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\intekhab alam\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\intekhab alam\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\intekhab alam\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\intekhab alam\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.0)
Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl (350.9 MB)
   ---------------------------------------- 0.0/350.9 MB ? eta -:--:--
   ---------------------------------------- 1.8/350.9 MB 10.1 MB/s eta 0:00:35
   ---------------------------------------- 3.9/350.9 MB 9.4 MB/s eta 0:00:37
    --------------------------------------- 5.8/350.9 MB 9.0 MB/s eta 0:00:39
    --------------------------------------- 7.6/350.9 MB 9.0 MB/s eta 0:00:39
   - -------------------------------------- 9.7/350.9 MB 9.2 MB/s eta 0:00:38
   - -------------------------------------- 11.5/350.9 MB 9.0 MB/s eta 0:00:38
   - -------------------------------------- 13.4/350.9 MB 9.0 MB/s eta 0:00:38
   - -------------------------------------- 15.5/350.9 MB 9.1 MB/s eta 0:00:37
   - -------------------------------------- 17.0/350.9 MB 9.0 MB/s eta 0:00:38
   -- ------------------------------------- 18.6/350.9 MB 8.8 MB/s eta 0:00:38
   -- ------------------------------------- 20.2/350.9 MB 8.7 MB/s eta 0:00:39
   -- ------------------------------------- 22.3/350.9 MB 8.8 MB/s eta 0:00:38
   -- ------------------------------------- 24.4/350.9 MB 8.9 MB/s eta 0:00:37
   --- ------------------------------------ 26.7/350.9 MB 9.0 MB/s eta 0:00:36
   --- ------------------------------------ 28.6/350.9 MB 9.1 MB/s eta 0:00:36
   --- ------------------------------------ 30.7/350.9 MB 9.1 MB/s eta 0:00:36
   --- ------------------------------------ 32.0/350.9 MB 9.0 MB/s eta 0:00:36
   --- ------------------------------------ 33.3/350.9 MB 8.8 MB/s eta 0:00:37
   --- ------------------------------------ 34.9/350.9 MB 8.8 MB/s eta 0:00:37
   ---- ----------------------------------- 36.4/350.9 MB 8.7 MB/s eta 0:00:37
   ---- ----------------------------------- 37.7/350.9 MB 8.7 MB/s eta 0:00:37
   ---- ----------------------------------- 39.6/350.9 MB 8.7 MB/s eta 0:00:36
   ---- ----------------------------------- 41.4/350.9 MB 8.7 MB/s eta 0:00:36
   ---- ----------------------------------- 43.5/350.9 MB 8.7 MB/s eta 0:00:36
   ----- ---------------------------------- 45.4/350.9 MB 8.7 MB/s eta 0:00:36
   ----- ---------------------------------- 47.4/350.9 MB 8.8 MB/s eta 0:00:35
   ----- ---------------------------------- 49.8/350.9 MB 8.8 MB/s eta 0:00:35
   ----- ---------------------------------- 51.6/350.9 MB 8.9 MB/s eta 0:00:34
   ------ --------------------------------- 53.7/350.9 MB 8.9 MB/s eta 0:00:34
   ------ --------------------------------- 55.3/350.9 MB 8.8 MB/s eta 0:00:34
   ------ --------------------------------- 57.1/350.9 MB 8.9 MB/s eta 0:00:34
   ------ --------------------------------- 59.0/350.9 MB 8.9 MB/s eta 0:00:33
   ------ --------------------------------- 61.1/350.9 MB 8.9 MB/s eta 0:00:33
   ------- -------------------------------- 62.9/350.9 MB 8.9 MB/s eta 0:00:33
   ------- -------------------------------- 65.3/350.9 MB 8.9 MB/s eta 0:00:32
   ------- -------------------------------- 66.6/350.9 MB 8.9 MB/s eta 0:00:33
   ------- -------------------------------- 68.4/350.9 MB 8.9 MB/s eta 0:00:32
   -------- ------------------------------- 70.3/350.9 MB 8.9 MB/s eta 0:00:32
   -------- ------------------------------- 71.8/350.9 MB 8.8 MB/s eta 0:00:32
   -------- ------------------------------- 73.4/350.9 MB 8.8 MB/s eta 0:00:32
   -------- ------------------------------- 74.7/350.9 MB 8.7 MB/s eta 0:00:32
   -------- ------------------------------- 75.8/350.9 MB 8.7 MB/s eta 0:00:32
   -------- ------------------------------- 76.8/350.9 MB 8.6 MB/s eta 0:00:32
   -------- ------------------------------- 78.1/350.9 MB 8.5 MB/s eta 0:00:32
   --------- ------------------------------ 79.4/350.9 MB 8.5 MB/s eta 0:00:33
   --------- ------------------------------ 80.5/350.9 MB 8.4 MB/s eta 0:00:33
   --------- ------------------------------ 82.1/350.9 MB 8.4 MB/s eta 0:00:33
   --------- ------------------------------ 83.1/350.9 MB 8.3 MB/s eta 0:00:33
   --------- ------------------------------ 84.1/350.9 MB 8.2 MB/s eta 0:00:33
   --------- ------------------------------ 85.2/350.9 MB 8.2 MB/s eta 0:00:33
   --------- ------------------------------ 86.5/350.9 MB 8.2 MB/s eta 0:00:33
   ---------- ----------------------------- 88.3/350.9 MB 8.2 MB/s eta 0:00:33
   ---------- ----------------------------- 90.2/350.9 MB 8.2 MB/s eta 0:00:32
   ---------- ----------------------------- 92.0/350.9 MB 8.2 MB/s eta 0:00:32
   ---------- ----------------------------- 93.6/350.9 MB 8.2 MB/s eta 0:00:32
   ---------- ----------------------------- 95.4/350.9 MB 8.2 MB/s eta 0:00:32
   ----------- ---------------------------- 97.3/350.9 MB 8.2 MB/s eta 0:00:32
   ----------- ---------------------------- 99.1/350.9 MB 8.2 MB/s eta 0:00:31
   ----------- ---------------------------- 100.9/350.9 MB 8.2 MB/s eta 0:00:31
   ----------- ---------------------------- 103.0/350.9 MB 8.2 MB/s eta 0:00:31
   ----------- ---------------------------- 104.9/350.9 MB 8.2 MB/s eta 0:00:30
   ------------ --------------------------- 107.0/350.9 MB 8.3 MB/s eta 0:00:30
   ------------ --------------------------- 109.1/350.9 MB 8.3 MB/s eta 0:00:30
   ------------ --------------------------- 110.9/350.9 MB 8.3 MB/s eta 0:00:29
   ------------ --------------------------- 113.0/350.9 MB 8.3 MB/s eta 0:00:29
   ------------- -------------------------- 115.3/350.9 MB 8.4 MB/s eta 0:00:29
   ------------- -------------------------- 117.4/350.9 MB 8.4 MB/s eta 0:00:28
   ------------- -------------------------- 119.3/350.9 MB 8.4 MB/s eta 0:00:28
   ------------- -------------------------- 120.8/350.9 MB 8.4 MB/s eta 0:00:28
   ------------- -------------------------- 122.2/350.9 MB 8.4 MB/s eta 0:00:28
   -------------- ------------------------- 123.7/350.9 MB 8.3 MB/s eta 0:00:28
   -------------- ------------------------- 125.3/350.9 MB 8.3 MB/s eta 0:00:28
   -------------- ------------------------- 126.6/350.9 MB 8.3 MB/s eta 0:00:27
   -------------- ------------------------- 128.5/350.9 MB 8.3 MB/s eta 0:00:27
   -------------- ------------------------- 129.5/350.9 MB 8.3 MB/s eta 0:00:27
   -------------- ------------------------- 130.8/350.9 MB 8.3 MB/s eta 0:00:27
   --------------- ------------------------ 131.9/350.9 MB 8.2 MB/s eta 0:00:27
   --------------- ------------------------ 133.4/350.9 MB 8.2 MB/s eta 0:00:27
   --------------- ------------------------ 134.7/350.9 MB 8.2 MB/s eta 0:00:27
   --------------- ------------------------ 136.6/350.9 MB 8.2 MB/s eta 0:00:27
   --------------- ------------------------ 138.4/350.9 MB 8.2 MB/s eta 0:00:26
   --------------- ------------------------ 140.2/350.9 MB 8.2 MB/s eta 0:00:26
   ---------------- ----------------------- 141.8/350.9 MB 8.2 MB/s eta 0:00:26
   ---------------- ----------------------- 143.1/350.9 MB 8.2 MB/s eta 0:00:26
   ---------------- ----------------------- 145.0/350.9 MB 8.2 MB/s eta 0:00:26
   ---------------- ----------------------- 146.3/350.9 MB 8.1 MB/s eta 0:00:26
   ---------------- ----------------------- 147.8/350.9 MB 8.1 MB/s eta 0:00:25
   ----------------- ---------------------- 149.4/350.9 MB 8.1 MB/s eta 0:00:25
   ----------------- ---------------------- 151.0/350.9 MB 8.1 MB/s eta 0:00:25
   ----------------- ---------------------- 152.3/350.9 MB 8.1 MB/s eta 0:00:25
   ----------------- ---------------------- 153.6/350.9 MB 8.1 MB/s eta 0:00:25
   ----------------- ---------------------- 155.5/350.9 MB 8.1 MB/s eta 0:00:25
   ----------------- ---------------------- 157.3/350.9 MB 8.1 MB/s eta 0:00:24
   ------------------ --------------------- 159.1/350.9 MB 8.1 MB/s eta 0:00:24
   ------------------ --------------------- 160.4/350.9 MB 8.1 MB/s eta 0:00:24
   ------------------ --------------------- 161.7/350.9 MB 8.1 MB/s eta 0:00:24
   ------------------ --------------------- 163.3/350.9 MB 8.1 MB/s eta 0:00:24
   ------------------ --------------------- 165.2/350.9 MB 8.1 MB/s eta 0:00:24
   ------------------- -------------------- 167.2/350.9 MB 8.1 MB/s eta 0:00:23
   ------------------- -------------------- 168.8/350.9 MB 8.1 MB/s eta 0:00:23
   ------------------- -------------------- 170.4/350.9 MB 8.1 MB/s eta 0:00:23
   ------------------- -------------------- 171.7/350.9 MB 8.1 MB/s eta 0:00:23
   ------------------- -------------------- 173.3/350.9 MB 8.1 MB/s eta 0:00:23
   ------------------- -------------------- 174.6/350.9 MB 8.0 MB/s eta 0:00:22
   -------------------- ------------------- 175.6/350.9 MB 8.0 MB/s eta 0:00:22
   -------------------- ------------------- 177.2/350.9 MB 8.0 MB/s eta 0:00:22
   -------------------- ------------------- 179.3/350.9 MB 8.0 MB/s eta 0:00:22
   -------------------- ------------------- 181.1/350.9 MB 8.0 MB/s eta 0:00:22
   -------------------- ------------------- 183.5/350.9 MB 8.1 MB/s eta 0:00:21
   --------------------- ------------------ 184.8/350.9 MB 8.0 MB/s eta 0:00:21
   --------------------- ------------------ 186.4/350.9 MB 8.0 MB/s eta 0:00:21
   --------------------- ------------------ 188.0/350.9 MB 8.0 MB/s eta 0:00:21
   --------------------- ------------------ 190.1/350.9 MB 8.1 MB/s eta 0:00:20
   --------------------- ------------------ 191.4/350.9 MB 8.0 MB/s eta 0:00:20
   ---------------------- ----------------- 193.2/350.9 MB 8.0 MB/s eta 0:00:20
   ---------------------- ----------------- 194.5/350.9 MB 8.0 MB/s eta 0:00:20
   ---------------------- ----------------- 195.8/350.9 MB 8.0 MB/s eta 0:00:20
   ---------------------- ----------------- 196.9/350.9 MB 8.0 MB/s eta 0:00:20
   ---------------------- ----------------- 198.4/350.9 MB 8.0 MB/s eta 0:00:20
   ---------------------- ----------------- 199.8/350.9 MB 8.0 MB/s eta 0:00:19
   ---------------------- ----------------- 201.3/350.9 MB 8.0 MB/s eta 0:00:19
   ----------------------- ---------------- 203.2/350.9 MB 8.0 MB/s eta 0:00:19
   ----------------------- ---------------- 204.7/350.9 MB 8.0 MB/s eta 0:00:19
   ----------------------- ---------------- 206.0/350.9 MB 7.9 MB/s eta 0:00:19
   ----------------------- ---------------- 207.4/350.9 MB 7.9 MB/s eta 0:00:19
   ----------------------- ---------------- 209.5/350.9 MB 8.0 MB/s eta 0:00:18
   ------------------------ --------------- 211.3/350.9 MB 8.0 MB/s eta 0:00:18
   ------------------------ --------------- 213.4/350.9 MB 8.0 MB/s eta 0:00:18
   ------------------------ --------------- 215.7/350.9 MB 8.0 MB/s eta 0:00:17
   ------------------------ --------------- 216.8/350.9 MB 8.0 MB/s eta 0:00:17
   ------------------------ --------------- 218.4/350.9 MB 8.0 MB/s eta 0:00:17
   ------------------------- -------------- 219.4/350.9 MB 8.0 MB/s eta 0:00:17
   ------------------------- -------------- 221.2/350.9 MB 8.0 MB/s eta 0:00:17
   ------------------------- -------------- 222.8/350.9 MB 8.0 MB/s eta 0:00:17
   ------------------------- -------------- 224.4/350.9 MB 8.0 MB/s eta 0:00:16
   ------------------------- -------------- 226.5/350.9 MB 8.0 MB/s eta 0:00:16
   ------------------------- -------------- 227.8/350.9 MB 8.0 MB/s eta 0:00:16
   -------------------------- ------------- 229.9/350.9 MB 8.0 MB/s eta 0:00:16
   -------------------------- ------------- 232.0/350.9 MB 8.0 MB/s eta 0:00:15
   -------------------------- ------------- 234.1/350.9 MB 8.0 MB/s eta 0:00:15
   -------------------------- ------------- 235.4/350.9 MB 8.0 MB/s eta 0:00:15
   --------------------------- ------------ 237.0/350.9 MB 8.0 MB/s eta 0:00:15
   --------------------------- ------------ 238.6/350.9 MB 8.0 MB/s eta 0:00:15
   --------------------------- ------------ 239.9/350.9 MB 8.0 MB/s eta 0:00:14
   --------------------------- ------------ 241.4/350.9 MB 8.0 MB/s eta 0:00:14
   --------------------------- ------------ 242.5/350.9 MB 7.9 MB/s eta 0:00:14
   --------------------------- ------------ 243.5/350.9 MB 7.9 MB/s eta 0:00:14
   --------------------------- ------------ 244.8/350.9 MB 7.9 MB/s eta 0:00:14
   ---------------------------- ----------- 246.2/350.9 MB 7.9 MB/s eta 0:00:14
   ---------------------------- ----------- 247.7/350.9 MB 7.8 MB/s eta 0:00:14
   ---------------------------- ----------- 249.0/350.9 MB 7.8 MB/s eta 0:00:13
   ---------------------------- ----------- 250.3/350.9 MB 7.8 MB/s eta 0:00:13
   ---------------------------- ----------- 251.1/350.9 MB 7.8 MB/s eta 0:00:13
   ---------------------------- ----------- 251.7/350.9 MB 7.8 MB/s eta 0:00:13
   ---------------------------- ----------- 253.0/350.9 MB 7.7 MB/s eta 0:00:13
   ---------------------------- ----------- 254.3/350.9 MB 7.7 MB/s eta 0:00:13
   ----------------------------- ---------- 255.6/350.9 MB 7.7 MB/s eta 0:00:13
   ----------------------------- ---------- 256.6/350.9 MB 7.6 MB/s eta 0:00:13
   ----------------------------- ---------- 257.4/350.9 MB 7.6 MB/s eta 0:00:13
   ----------------------------- ---------- 257.9/350.9 MB 7.6 MB/s eta 0:00:13
   ----------------------------- ---------- 259.0/350.9 MB 7.6 MB/s eta 0:00:13
   ----------------------------- ---------- 260.6/350.9 MB 7.6 MB/s eta 0:00:12
   ----------------------------- ---------- 262.1/350.9 MB 7.6 MB/s eta 0:00:12
   ----------------------------- ---------- 262.9/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 264.2/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 265.3/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 266.9/350.9 MB 7.5 MB/s eta 0:00:12
   ------------------------------ --------- 268.2/350.9 MB 7.4 MB/s eta 0:00:12
   ------------------------------ --------- 269.5/350.9 MB 7.4 MB/s eta 0:00:11
   ------------------------------ --------- 270.5/350.9 MB 7.4 MB/s eta 0:00:11
   ------------------------------ --------- 271.3/350.9 MB 7.3 MB/s eta 0:00:11
   ------------------------------- -------- 272.1/350.9 MB 7.3 MB/s eta 0:00:11
   ------------------------------- -------- 272.9/350.9 MB 7.3 MB/s eta 0:00:11
   ------------------------------- -------- 274.7/350.9 MB 7.3 MB/s eta 0:00:11
   ------------------------------- -------- 276.3/350.9 MB 7.3 MB/s eta 0:00:11
   ------------------------------- -------- 277.6/350.9 MB 7.2 MB/s eta 0:00:11
   ------------------------------- -------- 278.9/350.9 MB 7.2 MB/s eta 0:00:10
   ------------------------------- -------- 280.0/350.9 MB 7.2 MB/s eta 0:00:10
   -------------------------------- ------- 281.5/350.9 MB 7.2 MB/s eta 0:00:10
   -------------------------------- ------- 283.4/350.9 MB 7.2 MB/s eta 0:00:10
   -------------------------------- ------- 284.7/350.9 MB 7.2 MB/s eta 0:00:10
   -------------------------------- ------- 286.0/350.9 MB 7.2 MB/s eta 0:00:10
   -------------------------------- ------- 287.3/350.9 MB 7.1 MB/s eta 0:00:09
   -------------------------------- ------- 288.9/350.9 MB 7.2 MB/s eta 0:00:09
   --------------------------------- ------ 289.9/350.9 MB 7.1 MB/s eta 0:00:09
   --------------------------------- ------ 291.2/350.9 MB 7.2 MB/s eta 0:00:09
   --------------------------------- ------ 292.3/350.9 MB 7.1 MB/s eta 0:00:09
   --------------------------------- ------ 293.3/350.9 MB 7.1 MB/s eta 0:00:09
   --------------------------------- ------ 294.9/350.9 MB 7.1 MB/s eta 0:00:08
   --------------------------------- ------ 296.5/350.9 MB 7.1 MB/s eta 0:00:08
   --------------------------------- ------ 297.3/350.9 MB 7.1 MB/s eta 0:00:08
   ---------------------------------- ----- 298.8/350.9 MB 7.2 MB/s eta 0:00:08
   ---------------------------------- ----- 299.9/350.9 MB 7.2 MB/s eta 0:00:08
   ---------------------------------- ----- 300.9/350.9 MB 7.1 MB/s eta 0:00:07

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\intekhab alam\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\intekhab alam\anaconda3\Lib\site-packages)
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\intekhab alam\anaconda3\Lib\site-packages\~=mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\intekhab alam\anaconda3\Lib\site-packages\~=mpy'.
  You can safely remove it manually.
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\intekhab alam\anaconda3\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.5.3 which is incompatible.
mlxtend 0.25.0 requires scipy>=1.16.3, but you have scipy 1.13.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.3 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.5.3 which is incompatible.
streamlit 1.37.1 requires packaging<25,>=20, but you have packaging 26.3 which is incompatible.
streamlit 1.37.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.5 which is incompatible.
streamlit 1.37.1 requires pillow<11,>=7.1.0, but you have pillow 12.3.0 which is incompatible.
streamlit 1.37.1 requires protobuf<6,>=3.20, but you have protobuf 7.36.2 which is incompatible.

In [2]:
import sys
!"{sys.executable}" -m pip install keras

Requirement already satisfied: keras in c:\users\intekhab alam\anaconda3\lib\site-packages (3.15.1)
Requirement already satisfied: absl-py in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (2.5.0)
Requirement already satisfied: numpy in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (2.5.3)
Requirement already satisfied: rich in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (13.7.1)
Requirement already satisfied: namex in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (3.11.0)
Requirement already satisfied: optree in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (0.20.0)
Requirement already satisfied: ml-dtypes in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (0.6.0)
Requirement already satisfied: packaging in c:\users\intekhab alam\anaconda3\lib\site-packages (from keras) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from optree->keras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from rich->keras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\intekhab alam\anaconda3\lib\site-packages (from rich->keras) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\intekhab alam\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.0)

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\intekhab alam\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\intekhab alam\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\intekhab alam\anaconda3\Lib\site-packages)

In [3]:
import tensorflow as tf
import keras 
print(tf.__version__)
print(keras.__version__)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject